version: "2.2"
services:
  jobmanager:
    image: flink:1.19.0-scala_2.12
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./src/main/resources:/opt/flink/resources

  taskmanager:
    image: flink:1.19.0-scala_2.12
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 5
    volumes:
      - ./src/main/resources:/opt/flink/resources

  postgres:
    image: postgres
    restart: "unless-stopped"
    ports:
      - "54321:5432"
    command: -c 'max_connections=200'
    environment:
      POSTGRES_PASSWORD: dev_pw
      POSTGRES_USER: dev_user
      POSTGRES_DB: default
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  python_dashboard:
    build:
      context: ./noaa_dashboards
      dockerfile: Dockerfile
    depends_on:
      - postgres